# Generated by Django 5.2.1 on 2025-05-19 23:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dimensionamento', '0007_cenariodimensionamento_concorrencia_chat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_turno', models.CharField(max_length=100, unique=True, verbose_name='Nome do Tipo de Turno')),
                ('duracao_jornada_total', models.DurationField(help_text='Formato: HH:MM:SS ou HH:MM. Ex: 06:20:00', verbose_name='Duração Total da Jornada')),
                ('duracao_pausa1', models.DurationField(default=datetime.timedelta(seconds=600), help_text='Formato: HH:MM:SS. Ex: 00:10:00', verbose_name='Duração Pausa 1')),
                ('inicio_pausa1_apos_x_tempo', models.DurationField(default=datetime.timedelta(seconds=3600), help_text='Formato: HH:MM:SS. Ex: 01:00:00 (inicia após 1h de trabalho)', verbose_name='Pausa 1 Inicia Após X Tempo de Trabalho')),
                ('duracao_pausa2', models.DurationField(default=datetime.timedelta(seconds=1200), help_text='Formato: HH:MM:SS. Ex: 00:20:00', verbose_name='Duração Pausa 2 (Principal)')),
                ('inicio_pausa2_apos_x_tempo', models.DurationField(default=datetime.timedelta(seconds=10800), help_text='Formato: HH:MM:SS. Ex: 03:00:00 (aproximadamente na metade para uma jornada de 6h)', verbose_name='Pausa 2 Inicia Após X Tempo de Trabalho')),
                ('duracao_pausa3', models.DurationField(default=datetime.timedelta(seconds=600), help_text='Formato: HH:MM:SS. Ex: 00:10:00', verbose_name='Duração Pausa 3')),
                ('inicio_pausa3_apos_x_tempo_da_pausa2', models.DurationField(default=datetime.timedelta(seconds=7200), help_text='Formato: HH:MM:SS. Ex: 02:00:00 (inicia 2h após o fim da pausa 2)', verbose_name='Pausa 3 Inicia Após X Tempo do Fim da Pausa 2')),
                ('tempo_produtivo_calculado', models.DurationField(blank=True, editable=False, null=True, verbose_name='Tempo Produtivo Calculado da Jornada')),
                ('ativo', models.BooleanField(default=True, verbose_name='Turno Ativo?')),
            ],
            options={
                'verbose_name': 'Tipo de Turno',
                'verbose_name_plural': 'Tipos de Turno',
                'ordering': ['nome_turno'],
            },
        ),
        migrations.CreateModel(
            name='AlocacaoTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio_efetiva_turno', models.TimeField(help_text='Hora real que este grupo de agentes inicia o turno.', verbose_name='Hora de Início Efetiva do Turno')),
                ('quantidade_agentes', models.PositiveIntegerField(default=1, verbose_name='Quantidade de Agentes Neste Turno/Horário')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('cenario_dimensionamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes_de_turnos', to='dimensionamento.cenariodimensionamento', verbose_name='Cenário de Dimensionamento Associado')),
                ('tipo_turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes', to='escalas.tipoturno', verbose_name='Tipo de Turno Selecionado')),
            ],
            options={
                'verbose_name': 'Alocação de Turno',
                'verbose_name_plural': 'Alocações de Turno',
                'ordering': ['cenario_dimensionamento', 'hora_inicio_efetiva_turno', 'tipo_turno__nome_turno'],
            },
        ),
    ]
