# Generated by Django 5.2.1 on 2025-05-17 19:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimensionamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenarioDimensionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cenario', models.CharField(max_length=100, unique=True, verbose_name='Identificação do Cenário')),
                ('data_referencia', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Referência do Cenário')),
                ('volume_chamadas_diario_base', models.PositiveIntegerField(blank=True, null=True, verbose_name='Volume de Chamadas Diário (Base para Distribuição)')),
                ('tma_segundos', models.PositiveIntegerField(verbose_name='Duração Média das Chamadas (TMA em segundos)')),
                ('nivel_servico_meta_percentual', models.FloatField(default=80.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Meta de Nível de Serviço (%)')),
                ('tempo_atendimento_meta_segundos', models.PositiveIntegerField(default=20, verbose_name='Tempo Meta para Atendimento (segundos)')),
                ('fator_shrinkage_total_calculado_percentual', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Fator de Shrinkage Total Aplicado (%)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cenário de Dimensionamento',
                'verbose_name_plural': 'Cenários de Dimensionamento',
                'ordering': ['-data_referencia', 'nome_cenario'],
            },
        ),
        migrations.CreateModel(
            name='ComponenteShrinkage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome do Componente de Shrinkage')),
                ('percentual_padrao', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Percentual Padrão (%)')),
            ],
            options={
                'verbose_name': 'Componente de Shrinkage',
                'verbose_name_plural': 'Componentes de Shrinkage',
            },
        ),
        migrations.RemoveField(
            model_name='resultadodimensionamento',
            name='parametros',
        ),
        migrations.CreateModel(
            name='IntervaloVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Início do Intervalo')),
                ('volume_estimado', models.PositiveIntegerField(default=0, verbose_name='Volume Estimado no Intervalo')),
                ('agentes_erlang', models.FloatField(blank=True, null=True, verbose_name='Agentes Calculados (Erlang)')),
                ('agentes_com_shrinkage', models.FloatField(blank=True, null=True, verbose_name='Agentes Necessários (c/ Shrinkage)')),
                ('cenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervalos_volume', to='dimensionamento.cenariodimensionamento')),
            ],
            options={
                'verbose_name': 'Volume por Intervalo',
                'verbose_name_plural': 'Volumes por Intervalo',
                'ordering': ['cenario', 'hora_inicio'],
                'unique_together': {('cenario', 'hora_inicio')},
            },
        ),
        migrations.CreateModel(
            name='ShrinkageAplicadoCenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual_aplicado', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Percentual Aplicado no Cenário (%)')),
                ('cenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes_shrinkage_aplicados', to='dimensionamento.cenariodimensionamento')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dimensionamento.componenteshrinkage')),
            ],
            options={
                'verbose_name': 'Shrinkage Aplicado ao Cenário',
                'verbose_name_plural': 'Shrinkages Aplicados aos Cenários',
                'unique_together': {('cenario', 'componente')},
            },
        ),
        migrations.DeleteModel(
            name='ParametrosDimensionamento',
        ),
        migrations.DeleteModel(
            name='ResultadoDimensionamento',
        ),
    ]
