# Generated by Django 5.2.1 on 2025-05-17 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimensionamento', '0002_cenariodimensionamento_componenteshrinkage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cenariodimensionamento',
            name='duracao_jornada_padrao_horas',
            field=models.FloatField(default=6.33, help_text='Ex: 6.33 para 6h20min, 8.0 para 8h.', verbose_name='Duração da Jornada Padrão (horas decimais)'),
        ),
        migrations.AddField(
            model_name='cenariodimensionamento',
            name='ftes_calculados_estimativa',
            field=models.FloatField(blank=True, null=True, verbose_name='Estimativa de FTEs Calculados'),
        ),
        migrations.AddField(
            model_name='cenariodimensionamento',
            name='minutos_produtivos_por_jornada',
            field=models.PositiveIntegerField(blank=True, help_text='Total de minutos que um agente está disponível para atendimento na jornada (descontando pausas não produtivas).', null=True, verbose_name='Minutos Produtivos Estimados por Jornada'),
        ),
    ]
