# Generated by Django 5.2.1 on 2025-05-18 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimensionamento', '0003_cenariodimensionamento_duracao_jornada_padrao_horas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componenteshrinkage',
            options={'ordering': ['nome'], 'verbose_name': 'Componente de Shrinkage', 'verbose_name_plural': 'Componentes de Shrinkage'},
        ),
        migrations.AlterModelOptions(
            name='shrinkageaplicadocenario',
            options={'ordering': ['cenario', 'componente__nome'], 'verbose_name': 'Shrinkage Aplicado ao Cenário', 'verbose_name_plural': 'Shrinkages Aplicados aos Cenários'},
        ),
        migrations.RemoveField(
            model_name='cenariodimensionamento',
            name='duracao_jornada_padrao_horas',
        ),
        migrations.RemoveField(
            model_name='cenariodimensionamento',
            name='minutos_produtivos_por_jornada',
        ),
        migrations.AddField(
            model_name='cenariodimensionamento',
            name='jornada_padrao_duracao',
            field=models.DurationField(default=datetime.timedelta(seconds=22800), help_text='Formato: HH:MM:SS ou HH:MM. Ex: 06:20:00 para 6h20min.', verbose_name='Duração da Jornada Padrão'),
        ),
        migrations.AddField(
            model_name='cenariodimensionamento',
            name='tempo_produtivo_estimado_duracao',
            field=models.DurationField(default=datetime.timedelta(seconds=19800), help_text='Formato: HH:MM:SS ou HH:MM. Descontando pausas não produtivas. Ex: 05:30:00.', verbose_name='Tempo Produtivo Estimado por Jornada'),
        ),
    ]
