# Generated by Django 5.2.1 on 2025-05-18 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimensionamento', '0004_alter_componenteshrinkage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervalovolume',
            name='nivel_servico_projetado_percentual',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Nível de Serviço Projetado (%)'),
        ),
        migrations.AddField(
            model_name='intervalovolume',
            name='ocupacao_projetada_percentual',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Ocupação Projetada (%)'),
        ),
    ]
