# Generated by Django 5.2.1 on 2025-05-18 21:42

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimensionamento', '0005_intervalovolume_nivel_servico_projetado_percentual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cenariodimensionamento',
            name='meta_campanha_ativo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='[ATIVO] Meta da Campanha (nº sucessos)'),
        ),
        migrations.AddField(
            model_name='cenariodimensionamento',
            name='taxa_contato_percentual_ativo',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='[ATIVO] Taxa de Contato (%)'),
        ),
        migrations.AddField(
            model_name='cenariodimensionamento',
            name='taxa_sucesso_contato_percentual_ativo',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='[ATIVO] Taxa de Sucesso por Contato Efetivo (%)'),
        ),
        migrations.AddField(
            model_name='cenariodimensionamento',
            name='tempo_medio_discagem_espera_seg_ativo',
            field=models.PositiveIntegerField(blank=True, default=15, null=True, verbose_name='[ATIVO] Tempo Médio Discagem/Espera por Tentativa (s)'),
        ),
        migrations.AddField(
            model_name='cenariodimensionamento',
            name='tipo_calculo',
            field=models.CharField(choices=[('RECEPTIVO_VOZ', 'Voz Receptivo (Erlang C)'), ('ATIVO_META', 'Ativo por Meta')], default='RECEPTIVO_VOZ', max_length=20, verbose_name='Tipo de Dimensionamento'),
        ),
        migrations.AddField(
            model_name='cenariodimensionamento',
            name='tmp_segundos_padrao',
            field=models.PositiveIntegerField(blank=True, default=30, null=True, verbose_name='TMP Padrão (Pós-Chamada em segundos)'),
        ),
        migrations.AlterField(
            model_name='cenariodimensionamento',
            name='jornada_padrao_duracao',
            field=models.DurationField(default=datetime.timedelta(seconds=22800), help_text='Formato: HH:MM:SS ou HH:MM. Ex: 06:20:00.', verbose_name='Duração da Jornada Padrão'),
        ),
        migrations.AlterField(
            model_name='cenariodimensionamento',
            name='nivel_servico_meta_percentual',
            field=models.FloatField(default=80.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='[RECEPTIVO] Meta de Nível de Serviço (%)'),
        ),
        migrations.AlterField(
            model_name='cenariodimensionamento',
            name='tempo_atendimento_meta_segundos',
            field=models.PositiveIntegerField(default=20, verbose_name='[RECEPTIVO] Tempo Meta para Atendimento (s)'),
        ),
        migrations.AlterField(
            model_name='cenariodimensionamento',
            name='tempo_produtivo_estimado_duracao',
            field=models.DurationField(default=datetime.timedelta(seconds=19800), help_text='Formato: HH:MM:SS ou HH:MM. Ex: 05:30:00.', verbose_name='Tempo Produtivo Estimado por Jornada'),
        ),
        migrations.AlterField(
            model_name='cenariodimensionamento',
            name='tma_segundos',
            field=models.PositiveIntegerField(default=180, verbose_name='TMA Padrão (Segundos)'),
        ),
        migrations.AlterField(
            model_name='cenariodimensionamento',
            name='volume_chamadas_diario_base',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='[RECEPTIVO] Volume de Chamadas Diário (Base)'),
        ),
    ]
