# Generated by Django 5.2.1 on 2025-05-19 02:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimensionamento', '0006_cenariodimensionamento_meta_campanha_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cenariodimensionamento',
            name='concorrencia_chat',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Quantos chats um agente pode atender simultaneamente.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='[CHAT] Concorrência Máxima por Agente'),
        ),
        migrations.AlterField(
            model_name='cenariodimensionamento',
            name='nivel_servico_meta_percentual',
            field=models.FloatField(default=80.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='[RECEPTIVO/CHAT] Meta de Nível de Serviço (%)'),
        ),
        migrations.AlterField(
            model_name='cenariodimensionamento',
            name='tempo_atendimento_meta_segundos',
            field=models.PositiveIntegerField(default=20, verbose_name='[RECEPTIVO/CHAT] Tempo Meta para Atendimento (s)'),
        ),
        migrations.AlterField(
            model_name='cenariodimensionamento',
            name='tipo_calculo',
            field=models.CharField(choices=[('RECEPTIVO_VOZ', 'Voz Receptivo (Erlang C)'), ('ATIVO_META', 'Ativo por Meta'), ('CHAT_RECEPTIVO', 'Chat Receptivo (Erlang C com Concorrência)')], default='RECEPTIVO_VOZ', max_length=20, verbose_name='Tipo de Dimensionamento'),
        ),
        migrations.AlterField(
            model_name='cenariodimensionamento',
            name='tmp_segundos_padrao',
            field=models.PositiveIntegerField(blank=True, default=30, null=True, verbose_name='TMP Padrão (Pós-Chamada/Chat em segundos)'),
        ),
        migrations.AlterField(
            model_name='cenariodimensionamento',
            name='volume_chamadas_diario_base',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='[RECEPTIVO/CHAT] Volume Diário (Base)'),
        ),
    ]
